name: opencca-build

on:
  push:
    branches: [opencca/main, opencca/systex25, opencca/next, opencca/rk3588-v5+v7]
  workflow_dispatch:

jobs:
  trigger-external:
    uses: opencca/ci-scripts/.github/workflows/build-linux.yml@opencca/main
    with:
      branch: ${{ github.ref_name }}
